#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-netdisco
Version  : 3.0.0
Release  : 38
URL      : https://files.pythonhosted.org/packages/65/ca/f9263e384128a973595dda4022c96cb89afab8a9a83435bc955ec6f23358/netdisco-3.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/65/ca/f9263e384128a973595dda4022c96cb89afab8a9a83435bc955ec6f23358/netdisco-3.0.0.tar.gz
Summary  : Discover devices on your local network
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-netdisco-license = %{version}-%{release}
Requires: pypi-netdisco-python = %{version}-%{release}
Requires: pypi-netdisco-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: netdisco
Provides: netdisco-python
Provides: netdisco-python3
BuildRequires : pypi(requests)
BuildRequires : pypi(zeroconf)

%description
## This library is deprecated. We will no longer release new versions, fix bugs or accept pull requests. If you are looking to make your Home Assistant integration discoverable, use [the zeroconf and SSDP manifest options](https://developers.home-assistant.io/docs/en/next/creating_integration_manifest.html#zeroconf).

%package license
Summary: license components for the pypi-netdisco package.
Group: Default

%description license
license components for the pypi-netdisco package.


%package python
Summary: python components for the pypi-netdisco package.
Group: Default
Requires: pypi-netdisco-python3 = %{version}-%{release}

%description python
python components for the pypi-netdisco package.


%package python3
Summary: python3 components for the pypi-netdisco package.
Group: Default
Requires: python3-core
Provides: pypi(netdisco)
Requires: pypi(requests)
Requires: pypi(zeroconf)

%description python3
python3 components for the pypi-netdisco package.


%prep
%setup -q -n netdisco-3.0.0
cd %{_builddir}/netdisco-3.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641458883
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-netdisco
cp %{_builddir}/netdisco-3.0.0/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-netdisco/4a606a34022a7ef2eab88e43148dd48547d3c017
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-netdisco/4a606a34022a7ef2eab88e43148dd48547d3c017

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
